# Generated by Django 4.1.2 on 2022-12-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['id']},
        ),
    ]
