# Generated by Django 4.1.2 on 2023-01-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('variants', 'Variants'), ('any_input', 'Any Input'), ('goto', 'Goto')], default='variants', max_length=20),
        ),
        migrations.AlterField(
            model_name='bot',
            name='description',
            field=models.TextField(null=True, verbose_name='Bot description'),
        ),
        migrations.AlterField(
            model_name='message',
            name='coordinate_x',
            field=models.IntegerField(verbose_name='Coordinate by x axis'),
        ),
        migrations.AlterField(
            model_name='message',
            name='coordinate_y',
            field=models.IntegerField(verbose_name='Coordinate by y axis'),
        ),
    ]
