# Generated by Django 4.1.2 on 2023-01-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_message_next_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='variable',
            field=models.TextField(null=True),
        ),
    ]
