# Generated by Django 4.1.2 on 2023-01-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_alter_variant_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='variable',
            field=models.TextField(blank=True, null=True),
        ),
    ]
