# Generated by Django 4.1.2 on 2023-01-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0014_alter_message_variable'),
        ('bots', '0014_bot_error_message'),
    ]

    operations = [
    ]
