# Generated by Django 4.1.2 on 2023-02-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0016_bot_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='must_be_started',
            field=models.BooleanField(default=False),
        ),
    ]
