# Generated by Django 4.1.2 on 2023-02-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0016_bot_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartedBotsStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bots_list', models.TextField(verbose_name='Started bots')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Started bots',
                'get_latest_by': ['created_at'],
            },
        ),
    ]
