# Generated by Django 4.1.2 on 2023-02-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0018_alter_bot_description_alter_bot_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='must_be_generated',
            field=models.BooleanField(default=True),
        ),
    ]
