# Generated by Django 4.1.2 on 2022-10-31 06:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Описание бота')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='messages_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='messages_videos/')),
                ('file', models.FileField(blank=True, null=True, upload_to='messages_files/')),
                ('coordinate_x', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Координата по оси x')),
                ('coordinate_y', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Координата по оси y')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bots.bot')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('current_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_variants', to='bots.message')),
                ('next_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_variants', to='bots.message')),
            ],
        ),
    ]
