# Generated by Django 4.1.2 on 2022-10-31 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_variant_next_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='next_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_variants', to='bots.message'),
        ),
    ]
