# Generated by Django 4.1.2 on 2022-11-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_start_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание бота'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
