# Generated by Django 4.1.2 on 2022-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_alter_bot_description_alter_bot_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
    ]
