# Generated by Django 4.1.2 on 2022-12-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_message_keyboard_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id']},
        ),
    ]
