# Generated by Django 4.1.2 on 2022-12-15 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_alter_variant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='bots.bot')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
