# Generated by Django 4.1.2 on 2023-01-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0010_message_message_type_alter_bot_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='next_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_messages', to='bots.message'),
        ),
    ]
