# Generated by Django 4.1.2 on 2023-01-16 14:57

from django.db import migrations, models


def update_field_length(apps, schema_editor):
    Variant = apps.get_model("bots", "Variant")
    for obj in Variant.objects.all():
        if len(obj.text) > 120:
            obj.text = obj.text[:120]
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_message_variable'),
    ]

    operations = [
        migrations.RunPython(update_field_length),
        migrations.AlterField(
            model_name='variant',
            name='text',
            field=models.CharField(max_length=120),
        ),

    ]
