# Generated by Django 4.1.2 on 2023-01-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    @staticmethod
    def _update_field_length(apps, schema_editor):
        Variant = apps.get_model("bots", "Variant")
        for obj in Variant.objects.all():
            if len(obj.text) > 120:
                obj.text = obj.text[:120]
                obj.save()

    dependencies = [
        ('bots', '0012_message_variable'),
    ]

    operations = [
        migrations.RunPython(_update_field_length),
        migrations.AlterField(
            model_name='variant',
            name='text',
            field=models.CharField(max_length=120),
        ),

    ]

